// ===== DATA =====
export const WORD_LISTS = {
	1: [
		"cat",
		"dog",
		"sun",
		"hat",
		"cup",
		"red",
		"big",
		"run",
		"fun",
		"bed",
		"box",
		"net",
		"pen",
		"pig",
		"van",
		"zoo",
		"ant",
		"bee",
		"cow",
		"fox",
		"owl",
		"rat",
		"bat",
		"bug",
		"egg",
		"jam",
		"leg",
		"mop",
		"nut",
		"pet",
		"rug",
		"tag",
		"web",
		"yam",
		"zip",
	],
	2: [
		"cake",
		"fish",
		"door",
		"tree",
		"bird",
		"moon",
		"star",
		"duck",
		"frog",
		"hand",
		"jump",
		"king",
		"lamp",
		"milk",
		"nose",
		"open",
		"pink",
		"queen",
		"rain",
		"shoe",
		"toy",
		"unicorn",
		"vase",
		"wall",
		"yarn",
		"zebra",
		"book",
		"candy",
		"dance",
		"eagle",
		"fairy",
		"gift",
		"happy",
		"ice",
		"jelly",
		"kite",
		"lion",
		"magic",
		"nest",
		"orange",
		"puppy",
		"quiet",
		"rose",
		"smile",
		"tiger",
		"under",
		"violet",
		"wolf",
		"xray",
		"yellow",
	],
	3: [
		"apple",
		"beach",
		"cloud",
		"dance",
		"earth",
		"flame",
		"garden",
		"honey",
		"island",
		"jewel",
		"kiwi",
		"lemon",
		"melon",
		"night",
		"ocean",
		"pearl",
		"queen",
		"robot",
		"shell",
		"tulip",
		"unicorn",
		"violet",
		"water",
		"xray",
		"yogurt",
		"zebra",
		"angel",
		"butterfly",
		"castle",
		"diamond",
		"emerald",
		"flower",
		"glitter",
		"heaven",
		"island",
		"jasmine",
		"kingdom",
		"lullaby",
		"moonlight",
		"nebula",
		"orchid",
		"paradise",
		"rainbow",
		"stardust",
		"treasure",
		"universe",
		"velvet",
		"wonder",
		"xylophone",
		"yesterday",
	],
	4: [
		"rainbow",
		"butterfly",
		"fireworks",
		"wonderful",
		"beautiful",
		"chocolate",
		"marshmallow",
		"sparkling",
		"glittering",
		"adventure",
		"enchanted",
		"fairyland",
		"starlight",
		"moonbeams",
		"daydreams",
		"treasure",
		"kingdom",
		"friendship",
		"happiness",
		"champion",
		"chocolate",
		"dandelion",
		"fantastic",
		"glistening",
		"jellybean",
		"lollypop",
		"macaroon",
		"mermaid",
		"nighttime",
		"parachute",
		"quest",
		"rosebud",
		"sunshine",
		"twilight",
		"underwater",
		"vacation",
		"waterfall",
		"xylophone",
		"yesterday",
		"zeppelin",
		"carousel",
		"dolphins",
		"elephant",
		"football",
		"gorgeous",
		"honeybee",
		"icecream",
		"juggling",
		"kangaroo",
		"laughter",
	],
	5: [
		"fantastical",
		"marvellous",
		"butterflies",
		"marshmallow",
		"chocolates",
		"adventures",
		"wonderland",
		"glistening",
		"champignon",
		"beautifully",
		"dandelion",
		"butterscotch",
		"jellybeans",
		"lollipops",
		"macaroons",
		"mermaids",
		"nightingale",
		"pirouettes",
		"rainbow",
		"sunflower",
		"twinkling",
		"underwater",
		"volleyball",
		"wonderful",
		"xenophobia",
		"youngsters",
		"zoological",
	],
};

export const LEVEL_CONFIG = {
	1: { words: 10, speed: 0.4, spawnRate: 3500, health: 5 },
	2: { words: 12, speed: 0.5, spawnRate: 3200, health: 5 },
	3: { words: 14, speed: 0.6, spawnRate: 3000, health: 5 },
	4: { words: 15, speed: 0.7, spawnRate: 2800, health: 5 },
	5: { words: 16, speed: 0.75, spawnRate: 2600, health: 5 },
	6: { words: 18, speed: 0.85, spawnRate: 2400, health: 5 },
	7: { words: 20, speed: 0.9, spawnRate: 2200, health: 4 },
	8: { words: 22, speed: 1.0, spawnRate: 2000, health: 4 },
	9: { words: 25, speed: 1.1, spawnRate: 1900, health: 4 },
	10: { words: 30, speed: 1.2, spawnRate: 1700, health: 3 },
};
export function getLevelConfig(lvl) {
	if (LEVEL_CONFIG[lvl]) return LEVEL_CONFIG[lvl];
	return {
		words: 30 + (lvl - 10) * 2,
		speed: Math.min(1.2 + (lvl - 10) * 0.08, 2.5),
		spawnRate: Math.max(1700 - (lvl - 10) * 50, 800),
		health: 3,
	};
}
export function getWordList(lvl) {
	const key = Math.min(lvl, 5);
	return WORD_LISTS[key] || WORD_LISTS[1];
}
// ===== WORD EMOJIS =====
export const WORD_EMOJIS = {
	cat: "🐱",
	dog: "🐶",
	sun: "☀️",
	hat: "🧢",
	cup: "☕",
	red: "🔴",
	big: "📏",
	run: "🏃",
	fun: "🎉",
	bed: "🛏️",
	box: "📦",
	net: "🕸️",
	pen: "✏️",
	pig: "🐷",
	van: "🚐",
	zoo: "🦁",
	ant: "🐜",
	bee: "🐝",
	cow: "🐮",
	fox: "🦊",
	owl: "🦉",
	rat: "🐀",
	bat: "🦇",
	bug: "🐛",
	egg: "🥚",
	jam: "🍓",
	leg: "🦵",
	mop: "🧹",
	nut: "🥜",
	pet: "🐕",
	rug: "🧶",
	tag: "🏷️",
	web: "🕸️",
	yam: "🍠",
	zip: "🤐",
	cake: "🎂",
	fish: "🐟",
	door: "🚪",
	tree: "🌳",
	bird: "🐦",
	moon: "🌙",
	star: "⭐",
	duck: "🦆",
	frog: "🐸",
	hand: "✋",
	jump: "🤸",
	king: "👑",
	lamp: "💡",
	milk: "🥛",
	nose: "👃",
	open: "📂",
	pink: "🩷",
	queen: "👸",
	rain: "🌧️",
	shoe: "👟",
	toy: "🧸",
	unicorn: "🦄",
	vase: "🏺",
	wall: "🧱",
	yarn: "🧵",
	zebra: "🦓",
	book: "📚",
	candy: "🍬",
	dance: "💃",
	eagle: "🦅",
	fairy: "🧚",
	gift: "🎁",
	happy: "😊",
	ice: "🧊",
	jelly: "🍇",
	kite: "🪁",
	lion: "🦁",
	magic: "✨",
	nest: "🪺",
	orange: "🍊",
	puppy: "🐶",
	quiet: "🤫",
	rose: "🌹",
	smile: "🙂",
	tiger: "🐯",
	under: "⬇️",
	violet: "🟣",
	water: "💧",
	xray: "🩻",
	yellow: "🟡",
	apple: "🍎",
	beach: "🏖️",
	cloud: "☁️",
	earth: "🌍",
	flame: "🔥",
	garden: "🏡",
	honey: "🍯",
	island: "🏝️",
	jewel: "💎",
	kiwi: "🥝",
	lemon: "🍋",
	melon: "🍈",
	night: "🌃",
	ocean: "🌊",
	pearl: "🦪",
	robot: "🤖",
	shell: "🐚",
	tulip: "🌷",
	yogurt: "🥛",
	angel: "😇",
	butterfly: "🦋",
	castle: "🏰",
	diamond: "💎",
	emerald: "❇️",
	flower: "🌸",
	glitter: "✨",
	heaven: "☁️",
	jasmine: "🌼",
	kingdom: "👑",
	lullaby: "🎵",
	moonlight: "🌙",
	nebula: "🌌",
	orchid: "🌺",
	paradise: "🏝️",
	rainbow: "🌈",
	stardust: "✨",
	treasure: "💰",
	universe: "🌌",
	velvet: "🪵",
	wonder: "🤩",
	xylophone: "🎹",
	yesterday: "📅",
	fireworks: "🎆",
	wonderful: "🤩",
	beautiful: "💐",
	chocolate: "🍫",
	marshmallow: "🍡",
	sparkling: "✨",
	glittering: "✨",
	adventure: "🗺️",
	enchanted: "✨",
	fairyland: "🧚",
	starlight: "⭐",
	moonbeams: "🌙",
	daydreams: "💭",
	friendship: "🤝",
	happiness: "😄",
	champion: "🏆",
	dandelion: "🌼",
	fantastic: "🤩",
	glistening: "✨",
	jellybeans: "🍬",
	lollypop: "🍭",
	macaroon: "🥐",
	mermaid: "🧜",
	nightingale: "🐦",
	saffron: "🟨",
	carrot: "🥕",
	mango: "🥭",
	peach: "🍑",
	grape: "🍇",
	coconut: "🥥",
	pizza: "🍕",
	burger: "🍔",
	donut: "🍩",
	cookie: "🍪",
	pancake: "🥞",
	cereal: "🥣",
	cheese: "🧀",
	bread: "🍞",
	salad: "🥗",
	soup: "🍲",
	spaghetti: "🍝",
	taco: "🌮",
	sushi: "🍣",
	noodle: "🍜",
};

export function getWordEmoji(word) {
	return WORD_EMOJIS[word.toLowerCase()] || "⭐";
}

