// ===== EXPANDED WORD BANKS =====
// Curated kid-friendly words organized by level difficulty

export const WORDS_LEVEL_1 = [
  // T24: Home Row Garden 🌸 — garden / nature words (3-5 letters, kid-friendly)
  // Original garden-ish 20 (kept as anchors so existing flows don't shift)
  "grass","salad","glass","hills","falls","kids","dads","gals","lads","glad",
  "dash","silk","hall","lass","flask","digs","skill","fills","sacks","flags",
  // Garden flowers
  "lily","rose","daisy","iris","tulip","poppy","bloom","petal","petals",
  // Garden plants + produce
  "leaf","leaves","seed","seeds","soil","mud","moss","fern","root","roots",
  "plant","plants","sprout","sage","dill","basil","mint","thyme","herb","herbs",
  // Garden critters + small creatures
  "bug","ant","bee","wasp","beetle","moth","worm","snail","slug","aphid",
  // Garden tools + actions
  "rake","hoe","dig","digs","plant","pots","pot","can","water","weed","weeds",
  // Garden scenes
  "pond","dew","rain","sun","sunny","shade","path","stone","stones","bench",
  "fence","gate","arch","shed","trail","wood","woods","glen","dell","hill",
  // Buds + growing
  "bud","buds","fluff","fluffy","nest","nests","bark","log","logs","mulch",
  // Kid-sized produce
  "pea","peas","corn","plum","pear","fig","figs","kale","beet","beets",
  "carrot","radish","onion","melon","apple","berry","grape",
];

export const WORDS_LEVEL_2 = [
  // T24: Top Row Sky ⬆️ — sky / flying / wind / weather words
  // Sky features
  "sky","sun","sunny","ray","rays","cloud","clouds","star","stars","moon","moonlit",
  "beam","beams","light","lights","glow","bright","fair","clear","dawn","dusk","twilight",
  "sunrise","sunset","rainbow","halo","comet","planet","orbit","horizon",
  // Flying things
  "fly","flew","flown","bird","birds","wing","wings","kite","kites","jet","jets",
  "plane","planes","owl","owls","hawk","hawks","robin","swallow","swift","swifts",
  "parrot","raven","dove","doves","eagle","eagles","falcon","sparrow","stork","crane",
  "butterfly","dragonfly","airplane","aircraft","aviator","pilot","winged",
  // Wind + motion
  "wind","windy","breeze","breezy","gust","gusts","gusty","air","airy",
  "blow","blows","float","floats","soar","soars","soared","glide","glides",
  "drift","drifts","swoop","swoops","hover","hovers","swirl","swirls","twirl","twirls",
  // Sky + weather
  "high","higher","up","upon","upward","above","tall","taller","tower","towers",
  "pure","purely","quiet","quietly","quieter","out","outer",
  "type","typed","types","writer","wrote","write","written",
  "tour","tours","your","yours","tire","tires","tired",
  "wire","wires","wired","wiring","wiper",
  "year","years","yearly","yearn","yearns","yearned",
  "route","routes","routed","router","rout",
  "poet","poets","poetry","poetic",
  "pie","pies","pier","piers","pierce",
  "power","powerful","powerless","pour","pours","poured","pouring",
  "quote","quoted","quotes","pout","pouty",
  "ripe","riper","ripen","ripens",
  "equity","equal","equate","equation","equator",
  "true","truer","truest","truly","truce",
  "triple","triplet","tripod","trip","trips",
  "riot","riots","peer","peers","peered",
  "eye","eyes","eyed","eyeing","eyelid","eyelid",
  "yodel","yodels","youth","youthful","yourselves",
  "with","wither","withered","withering","withering",
  "wider","widen","widens","quietest","quietude",
  "worry","worrier","worries","worried",
  "wore","worn","worry","yore","yours",
];

export const WORDS_LEVEL_3 = [
  // T24: Bottom Row Ocean ⬇️ — sea / ocean / wave words
  // Ocean basics
  "sea","seas","ocean","oceans","wave","waves","wavy","tide","tides","tidal",
  "beach","coast","shore","sand","sandy","bay","bays","reef","reefs","kelp",
  "coral","current","depth","deep","shallow","shoal","pebble","pebbles","shell","shells",
  // Sea creatures
  "crab","crabs","clam","clams","fish","fishes","starfish","jellyfish","seal","seals",
  "whale","whales","dolphin","dolphins","shark","sharks","octopus","squid","lobster","eel",
  "eels","shrimp","prawn","ray","rays","manta","turtle","turtles","seahorse","seahorses",
  "snail","snails","slug","slugs","worm","worms","barnacle","barnacles","coral","anemone",
  // Movement + actions
  "swim","swims","swam","dive","dives","dove","splash","splashes","surf","surfs",
  "surfed","float","floats","sank","sink","sinks","sunk","drown","drowns","paddle",
  "paddles","rowed","sail","sails","sailed","sailing","cruise","cruises","cruised","cruising",
  "drift","drifts","drifted","float","floats","floaty","bob","bobs","bobbed","bobbing",
  "ride","rides","rode","rideable","sneak","sneaks","snuck","creep","creeps","crept",
  "wake","wakes","woke","woken","splashy","wash","washes","washed","washing","wade",
  "wades","waded","wading","wadeable","wade","river","rivers","pond","ponds","lake","lakes",
  "brook","creek","stream","streams","water","watery","wet","wets","wetter","wetting",
  "blow","blows","breath","breaths","breathe","breathes","breathed","bubble","bubbles",
  "bubbled","seaweed","kelp","algae","plankton","mollusk","mollusks","urchin","urchins",
  "scallop","scallops","mussel","mussels","oyster","oysters","clam","clams","periwinkle",
  "sponge","sponges","anemone","anemones","dugong","manatee","narwhal","beluga",
  "orca","porpoise","penguin","penguins","puffin","puffins","pelican","pelicans",
  // Boat + ship
  "boat","boats","ship","ships","canoe","canoes","kayak","kayaks","raft","rafts","rafted",
  "rowboat","sailboat","yacht","yachts","sub","submarine","submarines","tug","tugboat",
  "anchor","anchors","mooring","pier","piers","dock","docks","harbor","harbors","port","ports",
  "marina","lighthouse","lighthouses","buoy","buoys","navy","naval","captain","crew",
  "ferry","ferries","yacht","rowboat","motorboat","houseboat",
  // Adventure
  "diver","divers","scuba","snorkel","snorkels","mask","masks","fins","flipper","flippers",
  "expedition","expeditions","voyage","voyages","voyager","voyagers","cruise","cruises",
  "dive","dives","dived","diving","underwater","under","below","beneath","deep","deeply",
  "bottom","deep","depths","abyss","trench","trenches","oceanic","marine","naval",
  "magic","maze","mazes","zigzag","zigzags","zigzagged","zest","zesty","zen","zenith",
  "zoo","zoom","zooms","zoomed","zebra","zebras","zany","zaps","zapped","zapper",
  "zip","zips","zipped","zipper","zippers","zest","zero","zeros","zestful","zeal","zealous",
];

export const WORDS_LEVEL_4 = [
  // T24: All Letters Forest 🌲 — forest / nature words (uses all 26 letters)
  // Forest essentials
  "fox","tree","trees","run","bear","leaf","leaves","jump","deer","wood",
  "woods","owl","grass","acorn","cub","hide","pond","frog","climb","berry",
  "wolf","moss","bunny",
  // Forest + trails
  "forest","forests","trail","trails","path","paths","grove","groves","glen","glens",
  "dell","dells","clearing","wild","wilderness","wildwood","wilds","woodland","woodlands",
  "thicket","thickets","underbrush","understory","canopy","canopies","fern","ferns",
  "bramble","brambles","briar","briers","bush","bushes","shrub","shrubs",
  // Mountain + geography
  "mountain","mountains","mount","hill","hills","ridge","ridges","peak","peaks",
  "summit","summits","valley","valleys","cliff","cliffs","crag","crags","rock","rocks",
  "boulder","boulders","stone","stones","cave","caves","cavern","caverns","creek","creeks",
  "brook","brooks","stream","streams","river","rivers","waterfall","waterfalls","pond","ponds",
  "lake","lakes","meadow","meadows","field","fields","clearing",
  // Plants + flowers
  "pine","pines","oak","oaks","maple","maples","birch","birches","cedar","cedars",
  "elm","elms","ash","aspen","aspens","willow","willows","reed","reeds","reed","reeds",
  "fern","ferns","ivy","mossy","mosses","lichen","fungi","fungus","mushroom","mushrooms",
  "toadstool","toadstools","lichen","wildflower","wildflowers","lily","lilies",
  "daisy","daisies","rose","roses","poppy","poppies","violet","violets","clover","clovers",
  "bluebell","bluebells","sunflower","sunflowers","marigold","marigolds","petal","petals",
  "bloom","blooms","blossom","blossoms","sprout","sprouts","sapling","saplings",
  "twig","twigs","branch","branches","limb","limbs","trunk","trunks","bark","root","roots",
  "stump","stumps","log","logs","stick","sticks",
  // Forest creatures
  "fox","foxes","bear","bears","deer","doe","fawn","fawns","elk","moose",
  "wolf","wolves","coyote","coyotes","lynx","bobcat","bobcats","otter","otters",
  "beaver","beavers","mink","minks","weasel","weasels","marten","fox","rabbit","rabbits",
  "hare","hares","squirrel","squirrels","chipmunk","chipmunks","mouse","mice",
  "rat","rats","badger","badgers","raccoon","raccoons","skunk","skunks","porcupine",
  "hedgehog","hedgehogs","mole","moles","shrew","shrews","bat","bats",
  "owl","owls","hawk","hawks","eagle","eagles","falcon","falcons","raven","ravens",
  "crow","crows","robin","robins","sparrow","sparrows","finch","finches","wren","wrens",
  "thrush","thrushes","bluebird","bluebirds","cardinal","cardinals","jay","jays",
  "woodpecker","woodpeckers","hummingbird","hummingbirds","songbird","songbirds",
  "salamander","salamanders","newt","newts","frog","frogs","toad","toads",
  "turtle","turtles","snake","snakes","viper","vipers","adder","adders",
  "lizard","lizards","gecko","geckos","snail","snails","slug","slugs",
  "worm","worms","caterpillar","caterpillars","butterfly","butterflies",
  "moth","moths","beetle","beetles","ladybug","ladybugs","ant","ants",
  "bee","bees","wasp","wasps","hornet","hornets","cricket","crickets",
  "grasshopper","grasshoppers","dragonfly","dragonflies","firefly","fireflies",
  // Weather + sky over forest
  "sun","sunny","sunshine","shade","shadow","shadows","light","lights",
  "rain","rains","rainy","rainfall","drop","drops","dew","drizzly","mist","misty",
  "fog","foggy","cloud","clouds","cloudy","breeze","breezy","wind","windy",
  "gust","gusts","storm","storms","stormy","thunder","thunderstorm","lightning",
  "rainbow","rainbows","sunset","sunrise","twilight","dusk","dawn","moon","moonlight",
  "star","stars","starlight","starlit","sky","weather","climate",
  // Movement + actions
  "run","runs","ran","jump","jumps","jumped","leap","leaps","leaped","hop","hops",
  "hopped","skip","skips","skipped","walk","walks","walked","stroll","strolls",
  "wander","wanders","wandered","roam","roams","roamed","roaming","hike","hikes",
  "hiked","hiking","climb","climbs","climbed","climbing","crawl","crawls","crawled",
  "creep","creeps","crept","sneak","sneaks","snuck","sneaking","prowl","prowls",
  "prowled","stalk","stalks","stalked","hunt","hunts","hunted","chase","chases",
  "chased","chasing","hide","hides","hid","hidden","rest","rests","rested",
  "sleep","sleeps","slept","sleeping","nest","nests","nestled","nestling","perch",
  "perched","perching","flutter","flutters","fluttered","flit","flits","flitted",
  "glide","glides","glided","soar","soars","soared","fly","flies","flew","flown",
  // Nature sounds + feels
  "rustle","rustles","rustled","whisper","whispers","whispered","crackle","crackles",
  "crackled","snap","snaps","snapped","creak","creaks","creaked","groan","groans",
  "echo","echoes","echoed","silence","silent","still","calm","peaceful","lush",
  "green","emerald","verdant","fresh","clean","pure","wild","free","alive","glowing",
  "dappled","golden","amber","bronze","crimson","scarlet","azure","indigo","violet",
  // Forest scenes
  "camp","camped","camping","cabin","cabins","lodge","lodges","tent","tents",
  "fire","fires","campfire","campfires","torch","torches","lantern","lanterns",
  "compass","map","maps","trail","signs","signposts","beacon","beacons",
  "marker","markers","cairn","cairns","milepost","waystone","crossroad","crossroads",
  "adventure","adventures","explore","explores","explored","exploring","discover",
  "discovers","discovered","discovery","discoveries","venture","ventures","journey",
  "journeys","travel","travels","traveler","travelers","wanderer","wanderers",
  // Treasure + finds
  "treasure","treasures","gem","gems","crystal","crystals","pearl","pearls","gold",
  "silver","copper","ruby","sapphire","emerald","diamond","diamonds","jewel","jewels",
  "ancient","old","elder","ancient","mystic","mystical","magic","enchanted","fairy",
];

export const WORDS_LEVEL_5 = [
  // T24: Capital City 🏙️ — capital-letter city / proper-noun words
  // City buildings + places
  "CAR","BUS","JET","CITY","TOWN","HOME","PARK","ROAD","RIDE","WALK",
  "SHOP","TAXI","HOUSE","TRAIN","PLANE","TOWER","DRIVE","STREET","BRIDGE","METRO",
  // City buildings expanded
  "SCHOOL","STORE","MALL","BANK","HOTEL","HOSPITAL","LIBRARY","MUSEUM","THEATER","STADIUM",
  "OFFICE","CHURCH","MARKET","BAKERY","DINER","CAFE","SALON","GYM","POOL","PARK",
  "GARAGE","STUDIO","FACTORY","WAREHOUSE","STATION","TERMINAL","AIRPORT","DOCK","PIER","PORT",
  "TOWER","CASTLE","PALACE","MANOR","CABIN","LODGE","INN","MOTEL","PLAZA","SQUARE",
  "BLOCK","BUILDING","SKYSCRAPER","APARTMENT","HOUSE","HOME","FLAT","COTTAGE","FARM","RANCH",
  // City vehicles
  "CAR","BUS","TAXI","TRUCK","VAN","SUV","BIKE","SCOOTER","MOPED","TRAIN",
  "TRAM","TROLLEY","SUBWAY","METRO","PLANE","JET","HELICOPTER","SLED","SKATE","BOARD",
  "BOAT","SHIP","FERRY","YACHT","CAB","RIDE","LIMO","WAGON","BUGGY","CARTS",
  "CARTS","CART","TRAILER","TRACTOR","TRACTORS","BULLDOZER","CRANE","DUMP","TANK","WAGON",
  // City people (jobs as proper nouns)
  "DOCTOR","NURSE","TEACHER","CHEF","BAKER","FARMER","GUARD","POLICE","CHIEF","MAYOR",
  "JUDGE","LAWYER","JURY","CLERK","WORKER","DRIVER","PILOT","CAPTAIN","SAILOR","SOLDIER",
  "PAINTER","ARTIST","SINGER","DANCER","ACTOR","WRITER","POET","AUTHOR","READER","STUDENT",
  "MECHANIC","PLUMBER","ELECTRICIAN","CARPENTER","MASON","WELDER","TAILOR","SEAMSTRESS","DESIGNER","FLORIST",
  "BARBER","HAIR","STYLIST","BANKER","TRADER","CASHIER","MANAGER","BOSS","OWNER","PARTNER",
  "WAITER","HOSTESS","SOMMELIER","CATERER","COOK","BUTCHER","FISHER","HUNTER","RANGER","SCOUT",
  "KING","QUEEN","PRINCE","PRINCESS","DUKE","EARL","LORD","LADY","KNIGHT","SQUIRE",
  // City actions
  "WALK","DRIVE","RIDE","RUN","JUMP","STOP","GO","WAIT","PAY","BUY",
  "SELL","SHOP","WORK","PLAY","STAY","LEAVE","ARRIVE","ENTER","EXIT","VISIT",
  "EAT","DRINK","SLEEP","REST","READ","WRITE","DRAW","PAINT","SING","DANCE",
  "WATCH","LOOK","SEE","HEAR","LISTEN","TALK","SPEAK","SAY","TELL","ASK",
  "ANSWER","HELP","SAVE","CARE","LOVE","HATE","WANT","NEED","LIKE","HOPE",
  "OPEN","CLOSE","START","STOP","GO","COME","BRING","TAKE","GIVE","GET",
  "PUT","PUSH","PULL","LIFT","DROP","CATCH","THROW","KICK","HIT","MOVE",
  // Proper nouns: days + months
  "MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY","SUNDAY",
  "JANUARY","FEBRUARY","MARCH","APRIL","MAY","JUNE","JULY","AUGUST",
  "SEPTEMBER","OCTOBER","NOVEMBER","DECEMBER",
  "SPRING","SUMMER","AUTUMN","WINTER",
  // Directions (proper)
  "NORTH","SOUTH","EAST","WEST","UP","DOWN","LEFT","RIGHT","CENTER","MIDDLE",
  "ABOVE","BELOW","BESIDE","ACROSS","AROUND","THROUGH","INTO","OVER","UNDER","BEFORE",
  // Common proper-noun kids know
  "APPLE","BANANA","GRAPE","LEMON","MANGO","MELON","PEACH","PEAR","PLUM","BERRY",
  "CHERRY","FIGS","KIWI","LIME","OLIVE","GUAVA","PAPAYA",
  "DOG","CAT","BIRD","FISH","BEAR","LION","TIGER","WOLF","FOX","DEER",
  "FROG","DUCK","SWAN","HAWK","EAGLE","OWL","CROW","DOVE",
  "RED","BLUE","GREEN","PINK","GOLD","GRAY","BROWN","BLACK","WHITE","IVORY",
  "BEIGE","CORAL","PEACH","RUST","SLATE","AZURE","AMBER","JADE","TEAL","NAVY",
  // Numbers as capitals
  "ONE","TWO","THREE","FOUR","FIVE","SIX","SEVEN","EIGHT","NINE","TEN",
  "ELEVEN","TWELVE","TWENTY","THIRTY","FORTY","FIFTY","HUNDRED",
  // City-life adjectives
  "FAST","SLOW","QUICK","RAPID","SWIFT","SPEEDY","HASTY","BRISK","SPEED","PACE",
  "RUSH","RACE","CHASE","HURRY","ZOOM","DASH","DART","SPRINT",
  "BIG","SMALL","LARGE","TINY","TALL","SHORT","LONG","WIDE","NARROW","DEEP",
  "HIGH","LOW","OLD","NEW","YOUNG","FRESH","CLEAN","DIRTY","NEAT","TIDY",
  "HAPPY","SAD","GLAD","MAD","GLUM","CALM","QUIET","LOUD","BRIGHT","DARK",
  "HOT","COLD","WARM","COOL","WET","DRY","SOFT","HARD","SMOOTH","ROUGH",
  "EASY","HARD","SOFT","TIGHT","LOOSE","HEAVY","LIGHT","FULL","EMPTY","OPEN",
  "SAFE","DARK","BRIGHT","SHARP","DULL","QUICK","SLOW","EARLY","LATE","SOON",
  // Famous proper nouns
  "AMERICA","CANADA","MEXICO","BRAZIL","CHINA","JAPAN","FRANCE","ITALY","GERMANY","RUSSIA",
  "SPAIN","INDIA","KOREA","EGYPT","KENYA","INDIA","TURKEY","IRAN","IRAQ","PERU",
  // Name placeholders (generic, kid-safe)
  "JOHN","JANE","JIM","JEN","JOE","JESS","KATE","KATE","RYAN","LUCY",
  "MIKE","NICK","SARA","TONY","AMY","ANNA","BEN","BOB","DAN","EVA",
  "FRANK","GINA","HANK","IRIS","JADE","KARL","LEO","MIA","NOAH","OLIVER",
  "PAIGE","QUINN","ROSE","SAM","TARA","UMAR","VICKI","WILL","XENA","YARA","ZANE",
];

export const WORDS_LEVEL_6 = [
  // T24: Number Galaxy 🚀 — numbers + space/galaxy themed digits
  // Original 20 — kept as anchors
  "123","456","789","012","321","555","999","246","135","100","234","567","890","111","222","333","444","777","888","000",
  // Number patterns
  "101","202","303","404","505","606","707","808","909","1024","2048","360","180","90","45","30","15","60","120","240",
  "2000","2024","2025","3000","4000","5000","10000","1234","4321","5678","8765","1111","2222","3333","4444","5555","6666","7777","8888","9999",
  "007","911","411","119","999","112","211","311","411","511","611","711","811","911",
  "3.14","2.71","1.41","1.61","2.23","9.81","6.28","1.62","42","98","76","54","32","10","01","99","88","77","66","55",
  // Star + planet + galaxy numbers (kid-friendly space themed)
  "1ST","2ND","3RD","4TH","5TH","6TH","7TH","8TH","9TH","10TH",
  "11TH","12TH","13TH","20TH","21ST","22ND","23RD","100TH","1ST","2ND","3RD",
  "4.5","6.7","8.9","10.5","12.3","15.6","20.7","25.4","30.1","42.0",
  "100","200","300","400","500","600","700","800","900","1000",
  "10K","20K","50K","100K","1M","2M","5M","10M","100M","1B",
  "365","366","52","12","24","60","7","30","31","28",
  "911","411","311","711","811","112","113","114","115","116",
  "1942","1969","2000","2001","2020","2024","2050","2099","2100","3000",
  // Planet + galaxy proper-noun numbers
  "1AU","2AU","5AU","10AU","1.0","2.0","3.5","7.5","9.5","15.0",
  "M1","M2","M3","M4","M5","M6","M7","M8","M9","M10",
  "V1","V2","V3","V4","V5","V6","V7","V8","V9","V10",
  "100X","200X","500X","1000X","1X","2X","3X","4X","5X","6X",
  // Roman numerals
  "I","II","III","IV","V","VI","VII","VIII","IX","X",
  "XI","XII","XIII","XIV","XV","XVI","XVII","XVIII","XIX","XX",
  "L","C","D","M","XL","XC","CD","CM","XII","XXI",
  // Star + space counting
  "0.1","0.2","0.3","0.4","0.5","0.6","0.7","0.8","0.9","1.0",
  "1.1","1.2","1.3","1.4","1.5","1.6","1.7","1.8","1.9","2.0",
  "2.5","3.0","3.5","4.0","4.5","5.0","5.5","6.0","7.5","8.0",
  // Common large numbers
  "1000","2000","3000","4000","5000","10000","100000","1000000","10000000","100000000",
  // Phone-like
  "911","411","311","711","811","911","311","411","511","611",
  "111-1111","222-2222","333-3333","555-5555","777-7777","888-8888","999-9999","123-4567","234-5678","345-6789",
  // Time + math
  "12:00","1:00","2:30","3:45","4:15","5:30","6:00","7:15","8:45","9:00",
  "10:00","11:30","12:45","1:15","2:45","3:30","4:00","5:45","6:15","7:30",
  "8:00","9:15","10:30","11:45","12:15","1:30","2:00","3:00","4:30","5:00",
  "1+1","2+2","3+3","4+4","5+5","6+6","7+7","8+8","9+9","10+10",
  "1-1","2-1","3-1","4-1","5-1","6-1","7-1","8-1","9-1","10-1",
  "2*2","3*3","4*4","5*5","6*6","7*7","8*8","9*9","10*10","11*11",
  // Math expressions
  "1+1=2","2+2=4","3+3=6","4+4=8","5+5=10","6+6=12","7+7=14","8+8=16","9+9=18","10+10=20",
  "10-1=9","10-2=8","10-3=7","10-4=6","10-5=5","10-6=4","10-7=3","10-8=2","10-9=1","10-10=0",
  "2*2=4","3*3=9","4*4=16","5*5=25","6*6=36","7*7=49","8*8=64","9*9=81","10*10=100","11*11=121",
  "10/2=5","10/5=2","100/10=10","100/4=25","50/5=10","20/4=5","30/3=10","40/8=5","60/12=5","100/25=4",
];

export const WORDS_LEVEL_7 = [
  // T24: Speed Meadow ⚡ — meadow / fast / motion words (short, snappy)
  // Original 20 — kept as anchors
  "run","fox","bee","fly","sun","wing","leap","dash","deer","grass",
  "bloom","flit","dance","green","plant","happy","swift","chase","flower","gallop",
  // Speed words — short, snappy
  "jet","zip","zap","hop","pop","jog","log","bog","cog","dog",
  "fog","hog","jig","wig","gig","rig","fig","dig","big","pig",
  "tag","nag","wag","rag","bag","gag","jab","tab","cab","lab",
  "dab","fad","had","lad","pad","rad","sad","tad","van","ban",
  "can","fan","man","pan","ran","tan","vat","bat","cat","eat",
  "fat","hat","mat","pat","rat","sat","vat","war","bar","car",
  "ear","far","gar","jar","mar","oar","par","tar","air","fir",
  "sir","ace","ice","odd","add","aid","ale","ape","ate","awe",
  // Meadow + nature (kid-themed)
  "meadow","meadows","field","fields","grass","grasses","clover","clovers",
  "bloom","blooms","flower","flowers","blossom","blossoms","petal","petals",
  "stem","stems","leaf","leaves","root","roots","seed","seeds","sprout","sprouts",
  "bee","bees","butterfly","butterflies","ladybug","ladybugs","ant","ants",
  "grasshopper","grasshoppers","cricket","crickets","firefly","fireflies","moth","moths",
  "deer","fox","rabbit","hare","squirrel","chipmunk","mouse","mice",
  "hedge","fence","boulder","stone","stream","creek","pond","lake",
  "oak","elm","maple","willow","birch","cedar","pine","sapling",
  "fern","moss","lichen","ivy","reed","reeds","bulrush","bulrushes",
  "daisy","daisy","lily","lilies","rose","roses","violet","violets",
  "poppy","poppies","bluebell","bluebells","sunflower","sunflowers",
  "tulip","tulips","dandelion","dandelions","daisy","aster","asters",
  // Speed/motion words
  "dash","sprint","sprints","sprinted","dart","darts","darted","zoom","zooms","zoomed",
  "rush","rushes","rushed","race","races","raced","hurry","hurries","hurried",
  "leap","leaps","leaped","bound","bounds","bounded","spring","springs","sprang","sprung",
  "soar","soars","soared","swoop","swoops","swooped","glide","glides","glided",
  "swing","swings","swung","twirl","twirls","twirled","spin","spins","spun",
  "spin","spinning","whirl","whirls","whirled","flick","flicks","flicked",
  "blaze","blazes","blazed","flash","flashes","flashed","streak","streaks","streaked",
  "bolt","bolts","bolted","rocket","rockets","rocketed","charge","charges","charged",
  "blast","blasts","blasted","burst","bursts","burst","raced","racer","racers",
  // Movement verbs
  "run","runs","ran","jog","jogs","jogged","skip","skips","skipped","hop",
  "hops","hopped","bounce","bounces","bounced","march","marches","marched","stomp","stomps",
  "fly","flies","flew","flown","float","floats","floated","drift","drifts","drifted",
  "sail","sails","sailed","slide","slides","slid","slip","slips","slipped",
  "crawl","crawls","crawled","creep","creeps","crept","sneak","sneaks","snuck",
  "wander","wanders","wandered","roam","roams","roamed","stroll","strolls","strolled",
  "race","racer","racers","racing","runner","runners","racing","jumper","jumpers",
  // Short action adjectives
  "fast","slow","quick","rapid","swift","speedy","brisk","hasty","fleet","agile",
  "nimble","lithe","spry","active","alive","alert","aware","ready","set","go",
  "win","wins","won","victory","triumph","champion","hero","star","stars","shine",
  // Onomatopoeia-ish
  "zip","zap","pop","pow","wham","bang","crash","splash","whoosh","zoom",
  "vroom","beep","honk","toot","ding","dong","click","clack","tap","rap",
  // Common short words
  "yes","no","up","down","top","bottom","high","low","in","out",
  "on","off","go","stop","wait","come","here","there","now","then",
  "this","that","what","where","when","why","how","who","hi","bye",
  "cat","dog","fish","bird","fox","owl","bee","ant","bug","bat",
  "sun","moon","star","sky","cloud","rain","snow","wind","storm","ice",
  "red","blue","green","yellow","pink","gold","black","white","gray","brown",
  "one","two","six","ten","100","1000","first","second","third","last",
  "I","me","you","he","she","we","they","it","am","is","are","was","were",
  // Action phrases
  "run fast","go go","zip zap","hop pop","zip pop","zoom zoom","dash dash",
  "fly high","soar up","win big","go far","be quick","be brave","be bold",
  "stay sharp","stay calm","keep going","never quit","try again","one more",
  // Two/three-letter speeders
  "ax","ex","oh","ah","eh","hi","ok","go","no","so","up","us","we","by","my",
  "an","as","at","be","do","go","he","if","in","is","it","me","of","on","or",
  "to","up","we","so","no","go","ok","hi","oh","ah","ay","eh","ha","ho","ya",
  "ace","age","ago","aid","aim","air","all","and","ant","any","ape","arc","are","ark","arm",
  "art","ash","ask","ate","axe","bad","bag","ban","bar","bat","bay","bed","bet","bid","big",
  "bit","bow","box","boy","bud","bug","bun","bus","but","buy","cab","can","cap","car","cat",
  "cop","cow","cry","cub","cup","cut","dab","dad","dam","day","den","dew","did","dig","dim",
  "dip","dog","dot","dry","dub","dud","dug","duo","dye","ear","eat","egg","elf","elk","elm",
  "end","era","eve","eye","fab","fad","fan","far","fat","fax","fed","fee","few","fib","fig",
  "fin","fir","fit","fix","fly","fob","foe","fog","for","fox","fry","fun","fur","gab","gad",
];

export const WORDS_LEVEL_8 = [
  // T24: Accuracy Peak 🎯 — peak / climb / precision words (longer, careful)
  // Original 20 — kept as anchors
  "peak","hill","rock","climb","hike","path","trail","snow","ice","soar",
  "fly","wing","nest","bird","sky","brave","reach","top","view","gear",
  // Climbing + peak words
  "climber","climbers","climbing","climbed","climbable","ascend","ascends","ascended","ascending","ascent",
  "ascents","summit","summits","summited","summiting","pinnacle","pinnacles","peak","peaks","peaked",
  "mount","mounts","mounted","mounting","mountain","mountains","mountaintop","mountaintops","mountside","mountainside",
  "altitude","altitudes","elevation","elevations","crag","crags","craggy","cliff","cliffs","precipice",
  "ledge","ledges","outcrop","outcrops","ridgeline","ridgelines","ridgeback","ridge","ridges","ridgy",
  "spire","spires","needle","needles","pillar","pillars","column","columns","tower","towers",
  "summit","plateau","plateaus","mesa","mesas","butte","buttes","canyon","canyons","gorge","gorges",
  "ravine","ravines","valley","valleys","gulch","gulches","crevasse","crevasses","chasm","chasms",
  // Precision words
  "precise","precisely","precision","preciseness","accurate","accurately","accuracy","exact","exactly","exactness",
  "correct","correctly","correctness","careful","carefully","carefulness","cautious","cautiously","caution","cautions",
  "steady","steadily","steadiness","stable","stably","stability","balanced","balance","balances","balancing",
  "balancer","equilibrium","equilibriums","poise","poised","poises","centering","centered","centers","focus",
  "focuses","focused","focusing","focuser","refocus","refocused","refocusing","concentrate","concentrates","concentrated",
  "concentrating","concentration","deliberate","deliberately","deliberateness","measured","measure","measures","measuring",
  "measurer","metric","metrics","metrical","patient","patiently","patience","impatient","impatience","waiting",
  "waited","waits","await","awaits","awaited","awaiting","graceful","gracefully","gracefulness","elegant",
  "elegantly","elegance","smooth","smoothly","smoothness","fluid","fluidly","fluidity","controlled","control",
  "controls","controlling","controller","controllable","restrained","restrain","restrains","restraining","restraint","calm",
  // Mountain features
  "snow","snowy","snowfall","snowcap","snowcaps","snowfield","snowfields","avalanche","avalanches","glacier",
  "glaciers","iceberg","icebergs","icefall","icefalls","crevasse","crevasses","frost","frosty","frosted",
  "frosting","icicle","icicles","crystal","crystals","crystalline","alpine","alpines","altitude","altitudes",
  "treeline","timberline","tundra","tundras","permafrost","moraine","moraines","scree","talus","boulder",
  "boulders","rocky","rockfall","rockfall","stone","stones","stony","stoney","shale","slate",
  "granite","granites","basalt","basalts","obsidian","obsidians","quartz","quartzes","mineral","minerals",
  "feldspar","calcite","pyrite","gem","gemstone","gemstones","ore","ores","vein","veins",
  // Gear + equipment
  "rope","ropes","harness","harnesses","carabiner","carabiners","clamp","clamps","piton","pitons",
  "anchor","anchors","anchor","belay","belays","belayed","rappel","rappels","rappelled","rappelling",
  "crampon","crampons","ice","axe","axes","pickaxe","pickaxes","picks","spike","spikes",
  "helmet","helmets","goggles","glove","gloves","boots","boot","pack","packs","backpack",
  "backpacks","rucksack","rucksacks","lantern","lanterns","torch","torches","headlamp","headlamps","compass",
  "altimeter","altimeters","barometer","barometers","map","maps","guidebook","guidebooks","gps","tracker",
  // Mountain activities
  "hike","hiker","hikers","hiking","trek","treks","trekked","trekking","trekker","trekkers",
  "trail","trailhead","trailhead","path","pathway","pathways","route","routes","routed","routing",
  "climb","climbs","climbed","climbing","climber","climbers","scale","scales","scaled","scaling",
  "summit","summited","summiting","reach","reaches","reached","attain","attained","attains","attaining",
  "ascent","ascents","descent","descents","desend","descend","descended","descending","traverse","traverses",
  // Weather on peak
  "storm","storms","stormy","thunder","thunderstorm","thunderstorms","lightning","bolt","bolts","cloud",
  "clouds","cloudy","overcast","fog","foggy","mist","misty","drizzle","drizzly","hail","hailstorm",
  "wind","windy","gust","gusts","gale","gales","breeze","breezy","calm","tranquil",
  // Peak feelings
  "view","views","vista","vistas","panorama","panoramas","horizon","horizons","scenery","sceneries",
  "courage","courageous","courageously","brave","bravely","bravery","valiant","valiantly","valor","honor",
  "honor","honored","honoring","proud","pride","proudly","triumph","triumphant","triumphs","victory",
  "achievement","achievements","accomplish","accomplishes","accomplished","success","successes","succeed","succeeds",
  "determination","determined","determinedly","determines","persistence","persistent","persist","persists","perseverance",
  "persevering","endure","endures","endured","enduring","patience","patient","patiently","focused","focus",
  "steadily","calmly","gently","quietly","softly","slowly","quickly","rapidly","swiftly","speedily",
  "gracefully","elegantly","smoothly","carefully","cautiously","deliberately","intently","earnestly","sincerely",
  "earnest","sincere","solemn","solemnly","humble","humbly","meek","meekly","gentle","tenderly",
  "sturdy","sturdy","tough","tougher","toughest","strong","stronger","strongest","mighty","mightier",
  "mightiest","powerful","powerfully","forceful","forcefully","potent","potently","effective","effectively","fierce",
  "fiercely","fierceness","ferocious","ferociously","ferocity","wild","wilder","wildest","feral","savage",
  // Phrases
  "reach the peak","climb high","never give up","keep climbing","step by step","one step at a time",
  "breathe deep","stay focused","steady now","you can do it","almost there","keep going",
  "don't look down","eyes forward","one foot","then the other","steady wins","slow and steady",
];

export const WORDS_LEVEL_9 = [
  // T24: Master Valley ✨ — valley / cross / journey / mastery words
  // Original 20 — kept as anchors
  "vale","hill","bend","path","flow","swim","boat","fish","arch","over",
  "walk","tree","rock","moss","jump","sand","road","cool","deep","pond",
  // Valley + geography
  "valley","valleys","vale","vales","glen","glens","dell","dells","dale","dales",
  "hollow","hollows","basin","basins","bowl","bowls","trough","troughs","depression","depressions",
  "ravine","ravines","gorge","gorges","canyon","canyons","gulch","gulches","chasm","chasms",
  "crevasse","crevasses","gully","gullies","draw","draws","coulee","coulees","wash","washes",
  "creek","creeks","brook","brooks","stream","streams","river","rivers","spring","springs",
  "fountain","fountains","well","wells","spring","springs","pool","pools","pond","ponds",
  "lake","lakes","reservoir","reservoirs","marsh","marshes","swamp","swamps","bog","bogs",
  "fen","fens","meadow","meadows","field","fields","plain","plains","steppe","steppes",
  "prairie","prairies","pampas","savanna","savannas","tundra","tundras","heath","heaths",
  "moor","moors","downland","downs","upland","uplands","lowland","lowlands",
  // Bridge / crossing
  "bridge","bridges","arch","arches","arched","span","spans","deck","decks","plank","planks",
  "trestle","trestles","viaduct","viaducts","causeway","causeways","ford","fords","crossing","crossings",
  "tunnel","tunnels","culvert","culverts","passage","passages","pass","passes","gap","gaps",
  "step","steps","stepped","stepping","stair","stairs","stairway","stairways","staircase","staircases",
  "ladder","ladders","rung","rungs","rope","ropes","chain","chains","link","links",
  // Travel / journey
  "adventure","adventures","adventurer","adventuring","adventured","venture","ventures","ventured","venturing","venturer",
  "journey","journeys","journeyed","journeying","journeyer","travel","travels","traveled","traveling","traveler",
  "travelers","traveller","travellers","tour","tours","toured","touring","tourist","tourists","tourism",
  "explore","explores","explored","exploring","explorer","explorers","exploration","explorations","exploratory","expedition",
  "expeditions","expeditioner","expeditioners","excursion","excursions","trip","trips","outing","outings","voyage",
  "voyages","voyager","voyagers","passage","passages","pass","passes","wayfaring","wayfarer","wayfarers",
  "discover","discovers","discovered","discovering","discovery","discoveries","discoverer","discoverers","find","finds",
  "found","finder","finders","finding","findings","seek","seeks","sought","seeker","seekers",
  "seeking","search","searches","searched","searching","searcher","searchers","quest","quests","questing",
  // Cross / pass / ford
  "cross","crosses","crossed","crossing","crossings","crossroad","crossroads","intersection","intersections","junction",
  "junction","junctions","crosswise","across","over","past","beyond","between","among","through",
  "traverse","traverses","traversed","traversing","transverse","transverse","tramp","tramps","tramped","tramping",
  // Mastery + accomplishment
  "master","masters","mastery","mastered","mastering","masterful","masterfully","skillful","skillfully","skilled",
  "skill","skills","prowess","dexterity","adept","adepts","adeptly","expert","experts","expertly",
  "expertise","virtuoso","virtuosos","virtuous","virtuously","achieve","achieves","achieved","achieving","achiever",
  "achievers","achievement","achievements","accomplish","accomplishes","accomplished","accomplishment","accomplishments",
  "triumph","triumphs","triumphed","triumphal","triumphant","triumphantly","victory","victories","victor","victors",
  "victorious","victoriously","conquer","conquers","conquered","conquering","conqueror","conquerors","conquest","conquests",
  "champion","champions","championed","championing","championship","championships","winner","winners","winning","winnings",
  "glorious","gloriously","glory","glories","glorify","glorifies","glorified","glorifying","glorifier","gloriousness",
  "legend","legends","legendary","legendarily","legendless","myth","myths","mythic","mythical","mythically",
  "mythology","mythologies","epic","epics","epical","epically","fable","fables","fabled","folklore",
  "story","stories","storyteller","storytellers","storytelling","tale","tales","narrative","narratives","saga","sagas",
  "sagacious","sagacity","sage","sages","wisdom","wise","wiser","wisest","sapient","sapience",
  "brilliant","brilliantly","brilliance","brilliancy","bright","brightly","brightness","radiant","radiantly","radiance",
  "shining","shone","shine","shines","shiny","shinier","shiniest","gleam","gleams","gleaming",
  "gleamed","glow","glows","glowed","glowing","glower","glowering","gloomy","gloom","gloomier",
  "gloomiest","beacon","beacons","beaconed","beaconing","lamp","lamps","light","lights","lit",
  "luminous","luminosity","luminescence","luminescent","phosphor","phosphors","phosphorus","radiance","radiant","radiates",
  "magnificent","magnificently","magnificence","grand","grandly","grandness","majestic","majestically","majesty","majesties",
  "noble","nobly","nobility","nobleness","nobler","noblest","royal","royally","royalty","royalties",
  "regal","regally","regalia","regality","imperial","imperially","imperialness","princely","princelier","princeliest",
  "kingly","kinglier","kingliest","kingship","kingships","queenly","queenlier","queenliest","knightly","knightlier",
  "brave","bravely","braveness","courageous","courageously","courage","courages","valiant","valiantly","valor","valour",
  "hero","heroes","heroic","heroical","heroically","heroine","heroines","heroism","champion","champions",
  // Phrases
  "cross the valley","climb the hill","bridge the gap","find the path","reach the other side",
  "follow the stream","ford the river","span the gorge","tunnel through","over the bridge",
  "step by step","one foot forward","steady onward","keep moving","never look back",
  "venture forth","journey on","set forth","wander further","explore beyond","discover new",
  "master the way","rise above","shine bright","be the light","lead the way","show the path",
  "true north","steady aim","clear vision","firm resolve","strong will","steady heart",
];

export const WORDS_LEVEL_10 = [
  // T24: Legend Kingdom 🏆 — kingdom / legend / magic / hero words (hardest)
  // Original 20 — kept as anchors
  "king","queen","magic","spell","wand","flame","beast","roar","gold","gem",
  "chest","quest","hero","tower","knight","sword","fly","brave","river","woods",
  // Royalty + court
  "kingdom","kingdoms","kingly","kinglier","kingliest","kingship","kingships","royal","royally","royalty",
  "royalties","crown","crowns","crowned","crowning","crowns","throne","thrones","enthroned","enthroning",
  "prince","princes","princedom","princedoms","princess","princesses","princely","princelier","princeliest","princeling",
  "duke","dukes","dukedom","dukedoms","ducal","duchess","duchesses","duchy","duchies","earl",
  "earls","earldom","earldoms","marquis","marquises","marquess","marquesses","baron","barons","baroness",
  "baronesses","barony","baronies","count","counts","countess","countesses","counties","county","viscount",
  "lord","lords","lordship","lordships","lady","ladies","ladyship","ladyships","noble","nobles",
  "nobility","nobleman","noblemen","noblewoman","noblewomen","peer","peers","peerage","peerages","peeress",
  "peeresses","knight","knights","knighthood","knighthoods","knightly","knightlier","knightliest","squire","squires",
  "squirearchy","squirearchies","page","pages","pageant","pageantry","pageants","pageantry","pageantries","herald",
  "heralds","heraldry","heraldic","heraldries","marshal","marshals","marshalled","marshalling","chancellor","chancellors",
  "chancellery","chancelleries","steward","stewards","stewardship","stewardships","castellan","castellans","castellany","castellanies",
  "regent","regents","regency","regencies","regentess","regentesses","regentess","monarch","monarchs","monarchy",
  "monarchies","monarchic","monarchical","monarchically","sovereign","sovereigns","sovereignty","sovereignties","emperor","emperors",
  "empress","empresses","empire","empires","imperial","imperially","imperialness","imperialistic","imperialism","imperialist",
  "imperialists","czar","czars","czarina","czarinas","kaiser","kaisers","kaiserin","kaiserins","shah",
  "shahs","sultan","sultans","sultanate","sultanates","sultana","sultanas","caliph","caliphs","caliphate",
  "caliphates","pharaoh","pharaohs","pharaonic","pharaonical","pharaonically","rajah","rajahs","rani","ranis",
  "maharajah","maharajahs","maharaja","maharajas","maharanee","maharanis","maharishi","maharishis","emir","emirs",
  "emirate","emirates","sheikh","sheikhs","sheikhdom","sheikhdoms","sheik","sheiks","sheikdom","sheikdoms",
  // Dragons + beasts
  "dragon","dragons","dragonfly","dragonflies","draconic","draconian","firebreathing","firebreather","wyvern","wyverns",
  "drake","drakes","hydra","hydras","basilisk","basilisks","cockatrice","cockatrices","wyrm","wyrms",
  "griffin","griffins","griffon","griffons","phoenix","phoenixes","phoenixlike","pegasus","pegasuses","unicorn",
  "unicorns","unicornlike","kraken","krakens","leviathan","leviathans","chimera","chimeras","chimerical","sphinx",
  "sphinxes","sphinxic","sphynx","sphynxes","manticore","manticores","manticoric","behemoth","behemoths","behemothic",
  "leviathan","cetacean","cetaceans","cerberus","cerberuses","cerberic","cyclops","cyclopses","cyclopean","cyclopean",
  "titan","titans","titanic","titaness","titanesses","golem","golems","golemic","elemental","elementals",
  "djinn","djinns","djinni","djinnis","efreet","efreets","efriti","salamander","salamanders","sylph",
  "sylphs","sylphic","sylphid","sylphids","nymph","nymphs","nymphic","nymphical","dryad","dryads",
  "dryadic","faerie","faeries","faery","fae","faes","sprite","sprites","spriteful","pixie","pixies",
  "pixy","pixies","pixieish","imp","imps","impish","impishly","impishness","demon","demons",
  "demonic","demonical","demonically","devil","devils","devilish","devilishly","devilment","devilry","devilries",
  "fiend","fiends","fiendish","fiendishly","fiendishness","familiar","familiars","succubus","succubi","incubus",
  "incubi","vampire","vampires","vampiric","vampirism","lycanthrope","lycanthropes","lycanthropic","werewolf","werewolves",
  "ghost","ghosts","ghostly","ghostlier","ghostliest","phantom","phantoms","phantomlike","phantomish","specter",
  "specters","spectral","spectrally","specterlike","wraith","wraiths","wraithlike","wraithly","poltergeist","poltergeists",
  "poltergeistlike","apparition","apparitions","revenant","revenants","revenantlike","banshee","banshees","bansheelike",
  "shade","shades","shaded","shading","shadily","shadow","shadows","shadowed","shadowing","shadowy",
  // Castles + fortifications
  "castle","castles","castellan","castellans","fortress","fortresses","citadel","citadels","palace","palaces",
  "palatial","keep","keeps","keepable","bailey","baileys","battlement","battlements","battlemented","battlementing",
  "turret","turrets","turreted","turreting","bastion","bastions","bastioned","barbican","barbicans","drawbridge",
  "drawbridges","portcullis","portcullises","portcullised","moat","moats","moated","moating","curtain","curtains",
  "wall","walls","walled","walling","rampart","ramparts","ramparted","parapet","parapets","parapeted",
  "tower","towers","towered","towering","towerlike","spire","spires","steeple","steeples","steepled",
  "dungeon","dungeons","dungeonlike","dungeonic","dungeoness","dungeonesses","oubliette","oubliettes","dungeoner","dungeoneer",
  "dungeoneers","cellar","cellars","cellared","crypt","crypts","cryptic","cryptical","cryptically","catacomb",
  "catacombs","catacombed","cavern","caverns","cavernous","cavernously","caverned","grotto","grottoes","grottos",
  "cave","caves","caved","caver","cavers","caving","mine","mines","mined","miner","miners","mining",
  "minefield","minefields","tunnel","tunnels","tunneled","tunneling","tunneller","tunnellers","underground","undergrounds",
  "subterranean","subterraneous","subterraneously","underworld","underworlds","subworld","subworlds","underrealm","underrealms",
  // Magic + spellcraft
  "wizard","wizards","wizardry","sorcerer","sorcerers","sorcery","sorceress","sorceresses","enchanter","enchanters",
  "enchantress","enchantresses","enchantment","enchantments","enchanting","enchantingly","mage","mages","magus","magi",
  "magical","magically","magician","magicians","magic","magics","magicdom","magicaldom","warlock","warlocks",
  "warlockry","warlockies","witch","witches","witchy","witchier","witchiest","witchcraft","witcheries","witchery",
  "hex","hexes","hexed","hexing","hexer","hexers","hexagram","hexagrams","hexagonal","hexagonally",
  "hexahedron","hexahedrons","hexastyle","hexastyles","spell","spells","spelled","spelling","speller","spellers",
  "incantation","incantations","incant","incants","incanted","incanting","chant","chants","chanted","chanting",
  "charm","charms","charmed","charming","charmingly","charmer","charmers","amulet","amulets","amuletic",
  "talisman","talismans","talismanic","talismanical","talismanically","fetish","fetishes","fetishistic","fetishist","fetishists",
  "relic","relics","reliclike","relict","relicts","relicted","relicting","relicter","relicters","artifact",
  "artifacts","artifacted","artifacting","artefact","artefacts","curio","curios","curious","curiously","curiosity",
  "rune","runes","runed","runestone","runestones","runelike","runic","runical","runically","sigil",
  "sigils","sigilic","sigillic","scroll","scrolls","scrolled","scrolling","tome","tomes","tomeish",
  "tomeishness","codex","codices","codexlike","manuscript","manuscripts","manuscriptal","grimoire","grimoires","grimoireish",
  "wand","wands","wandlike","wandler","wandlers","wandling","staff","staffs","staved","staffed","staffing",
  "rod","rods","rodded","rodding","scepter","scepters","sceptered","sceptering","sceptre","sceptres",
  "orb","orbs","orbed","orbing","crystal","crystals","crystalline","crystallinity","crystallize","crystallizes",
  "crystallized","crystallizing","orbicular","orbicularly","crystalball","crystalballs","mirror","mirrors","mirrored","mirroring",
  "magic mirror","looking glass","speculum","speculums","specula","pool","pools","pooled","pooling","font",
  "fonts","fonted","fonting","cauldron","cauldrons","cauldroned","cauldroning","brew","brews","brewed",
  "brewing","brewer","brewers","brewery","breweries","potion","potions","potioned","potioning","elixir",
  "elixirs","elixirial","philter","philters","philtered","philtering","philtre","philtres","tonic","tonics",
  "tonicked","tonicking","remedy","remedies","remedied","remedying","cure","cures","cured","curing","curer",
  "curers","cursive","cursively","poison","poisons","poisoned","poisoning","poisoner","poisoners","poisonous",
  "venom","venoms","venomed","venoming","venomous","venomously","venomousness","antidote","antidotes","antidoted",
  "antidoting","counter","counters","countered","countering","counteract","counteracts","counteracted","counteracting","counteraction",
  "counteractions","ward","wards","warded","warding","warder","warders","wardship","wardships","safeguard",
  "safeguards","safeguarded","safeguarding","protect","protects","protected","protecting","protector","protectors","protection",
  "protections","protective","protectively","protectiveness","shield","shields","shielded","shielding","shieldlike","armor",
  "armors","armored","armoring","armorlike","armor-clad","mail","mailed","mailing","mail-clad","plate",
  "plates","plated","plating","plate-armor","mail-armor","buckler","bucklers","bucklered","bucklering","aegis",
  "aegises","aegis-like","talaric","talarian","talaric","aegis-clad","sigil","sigil-clad","warded","wyrd",
  "wyrds","wyrm","wyrms","wyrmkin","wyrmkins","wyrdness","fey","feydom","feydoms","feyish","feyly",
  // Heroes + quests
  "knight","knights","knightly","knightlier","knightliest","knighthood","knighthoods","knight-errant","knight-errantry","knightess",
  "squire","squires","squired","squiring","squireling","squirelings","page","pages","paged","paging","varlet",
  "varlets","varletlike","varletries","varletry","varletries","warrior","warriors","warrioress","warrioresses","warriorlike",
  "war","wars","wartime","wartimes","warring","warfare","battle","battles","battled","battling","battler",
  "battlers","fighter","fighters","fighting","fought","foughten","champion","champions","championed","championing",
  "hero","heroes","heroic","heroical","heroically","heroine","heroines","heroism","heroisms","antihero",
  "antiheroes","antiheroine","antiheroines","protagonist","protagonists","antagonist","antagonists","villain","villains","villainous",
  "villainously","villainess","villainesses","villainy","villainies","scoundrel","scoundrels","scoundrelly","scoundrelism","scoundrelisms",
  "rogue","rogues","roguish","roguishly","roguishness","rogueship","rogueships","rapscallion","rapscallions","rascal",
  "rascals","rascally","rascalism","rascalisms","knave","knaves","knavish","knavishly","knavishness","trickster",
  "tricksters","trickstering","tricksterism","tricksterisms","trick","tricks","tricked","tricking","trickish","trickishly",
  "merlin","merlins","merlinlike","merlin-esque","galahad","galahads","galahad-like","lancelot","lancelots","arthur",
  "arthurs","arthurian","camelot","camelots","camelotian","avalon","avalons","avalonian","excalibur","excaliburs",
  "round table","round-table","roundtabled","grail","grails","grail-like","holygrail","sanctgraal","sanctgraal-ish","sanct",
  "sanctity","sanctities","sanctorum","sanctorums","sanctuary","sanctuaries","sanctified","sanctifies","sanctify","sanctifying",
  "sanctification","sanctitude","sanctitudes","sanctimonious","sanctimoniously","sanctimoniousness","sacrament","sacraments","sacramental","sacramentally",
  // Treasures + valuables
  "treasure","treasures","treasured","treasuring","treasurer","treasurers","treasury","treasuries","treasureless","treasure-house",
  "jewel","jewels","jeweled","jeweling","jewelry","jewelries","jeweller","jewellers","jeweler","jewelers",
  "gemstone","gemstones","gemstoned","gemstoning","gemlike","gem","gems","gemmed","gemming","gemmiferous",
  "gemmiferousness","gemmiparous","gemmiparously","crystal","crystals","crystalline","crystallinity","crystalize","crystalizes","crystalized",
  "diamond","diamonds","diamonded","diamantine","diamantinely","ruby","rubies","rubied","ruby-red","sapphire",
  "sapphires","sapphirine","sapphirinely","emerald","emeralds","emeralded","emeraldine","emerald-green","topaz","topazes",
  "topazy","topazlike","opal","opals","opalescent","opalescently","opalescence","opalescences","amethyst","amethysts",
  "amethystine","amethystinely","pearl","pearls","pearled","pearling","pearly","pearlier","pearliest","mother-of-pearl",
  "nacre","nacres","nacreous","nacreously","nacreousness","gold","golden","goldenly","goldenness","goldish",
  "goldishness","gilded","gilding","gilds","gilder","gilders","silver","silvery","silverly","silvered",
  "silvering","silvers","silversmith","silversmiths","silversmithing","silversmithings","platinum","platinous","platinoid","platinoids",
  "copper","coppery","copperish","coppers","coppered","coppering","coppersmith","coppersmiths","bronze","bronzes",
  "bronzed","bronzing","bronzite","bronzites","bronzite-like","brass","brasses","brassy","brassier","brassiest",
  "iron","irons","ironed","ironing","ironic","ironical","ironically","steel","steels","steeled","steeling",
  "steelworker","steelworkers","steelwork","steelworks","steelworks","mithril","mithrils","mithrilic","mithril-like","adamant",
  "adamants","adamantine","adamantinely","adamantium","adamantiums","orichalcum","orichalcums","orichalcum-like","meteoric","meteorite",
  "meteorites","meteoritic","meteoric-iron","starlight","starlit","starlight-like","star-born","starlit-night","celestial","celestially",
  "celestialness","heavenly","heavenlier","heavenliest","heaven-sent","heaven-born","divine","divinely","divineness","divinity",
  "ethereal","ethereally","etherealness","immortal","immortals","immortality","immortalize","immortalizes","immortalized","immortalizing",
  // Battle + conflict
  "battle","battles","battled","battling","battler","battlers","war","wars","wartime","wartimes","warring",
  "warfare","warred","warrior","warriors","warrioress","warrioresses","warriorlike","combat","combats","combated",
  "combating","combatant","combatants","combat-ready","clash","clashes","clashed","clashing","clasher","clashers",
  "duel","duels","dueled","dueling","duelist","duelists","duelistship","duelistships","duello","duellos","duellos",
  "skirmish","skirmishes","skirmished","skirmishing","skirmisher","skirmishers","siege","sieges","besieged","besieging",
  "besieger","besiegers","siegecraft","siegeworks","siegework","raid","raids","raided","raiding","raider",
  "raiders","raiding-party","ambush","ambushes","ambushed","ambushing","ambusher","ambushers","surprise","surprised",
  "surprising","surprise-attack","charge","charges","charged","charging","charger","chargers","cavalry","cavalries",
  "cavalryman","cavalrymen","cavalier","cavaliers","cavalierly","cavalierness","infantry","infantries","infantryman","infantrymen",
  "footman","footmen","foot-soldier","foot-soldiers","archer","archers","archery","archeries","bowman","bowmen",
  "bow","bows","bowed","bowing","bowstring","bowstrings","arrow","arrows","arrowed","arrowing","arrowhead",
  "arrowheads","quiver","quivers","quivered","quivering","spear","spears","speared","spearing","spearhead",
  "spearheads","spearheaded","spearheading","lance","lances","lanced","lancing","lancer","lancers","halberd",
  "halberds","halberdier","halberdiers","pike","pikes","piked","piking","pikeman","pikemen","pike-square",
  "sword","swords","sworded","swordplay","swordplayings","swordsmanship","swordfighter","swordfighters","swordfighting","blade",
  "blades","bladed","blading","dagger","daggers","daggered","daggerring","dirk","dirks","dirked","dirking",
  "knife","knives","knifed","knifing","stiletto","stilettos","stilettoed","stilettoing","rapier","rapiers",
  "rapiered","rapiering","sabre","sabres","sabred","sabring","saber","sabers","sabered","sabering",
  "axe","axes","axed","axing","axeman","axemen","battleaxe","battleaxes","mace","maces","maced",
  "macing","mace-bearer","mace-bearers","mace-bearer-like","club","clubs","clubbed","clubbing","warhammer","warhammers",
  "hammered","hammering","flail","flails","flailed","flailing","morningstar","morningstars","morningstared","morningstaring",
  // Courage + virtue
  "courage","courageous","courageously","courages","brave","bravely","braveness","braver","bravest","bravery",
  "valor","valour","valorous","valorously","valiant","valiantly","valiantness","daring","daringly","daringness",
  "bold","boldly","boldness","bolder","boldest","fearless","fearlessly","fearlessness","intrepid","intrepidly",
  "intrepidness","dauntless","dauntlessly","dauntlessness","doughty","doughtiness","doughtily","doughty-hearted","lionhearted","lionheartedly",
  "lionheartedness","noble","nobly","nobility","nobleness","nobler","noblest","virtue","virtues","virtuous",
  "virtuously","virtuousness","honor","honors","honored","honoring","honorable","honorably","honour","honours",
  "honoured","honouring","respect","respects","respected","respecting","respectful","respectfully","respectfulness","admire",
  "admires","admired","admiring","admirer","admirers","admirable","admirably","esteem","esteems","esteemed",
  "esteeming","regard","regards","regarded","regarding","regardful","regardfully","revere","reveres","revered",
  "revering","reverence","reverences","reverenced","reverencing","reverent","reverently","reverential","reverentially","reverend",
  "venerate","venerates","venerated","venerating","veneration","venerations","venerable","venerableness","revered","sacred",
  "sacredly","sacredness","hallow","hallows","hallowed","hallowing","hallowedness","consecration","consecrations","blessed",
  "bless","blesses","blessed","blessing","blessings","blessedness","beatific","beatifically","beatification","beatifications",
  "holy","holier","holiest","holily","holiness","sanctity","sanctities","saint","saints","sainted","sainting",
  "saintly","saintlier","saintliest","saintliness","saintlike","saint-ship","saintlier","saintliest","martyr","martyrs",
  "martyred","martyring","martyrdom","martyrdoms","confessor","confessors","confessed","confessing","confession","confessions",
  "confessional","confessionals","sacrificial","sacrificially","sacrifice","sacrifices","sacrificed","sacrificing","sacrificial","offering",
  "offerings","offered","offer","offers","offerer","offerers","offeree","offerees","offeror","offerors",
  // Ancient + mystic
  "ancient","ancients","anciently","ancientness","ancienter","ancientest","antiquity","antiquities","antiquarian","antiquarians",
  "antiquated","antiquatedly","antiquatedness","elder","elders","elderly","elderliness","eldest","elderkin","elderkins",
  "elderly","primordial","primordially","primeval","primevally","primal","primally","primality","primalities","primitiveness",
  "primitive","primitives","primitively","primitivism","primitivisms","primitivist","primitivists","primordiality","primordialities","proto",
  "proto-human","proto-humans","proto-history","protohistoric","protohistorically","ancestral","ancestrally","ancestralness","ancestry","ancestries",
  "ancestor","ancestors","ancestored","ancestoring","ancestress","ancestresses","ancestral","ancestralness","mystic","mystics",
  "mystical","mystically","mysticality","mysticalities","mysticism","mysticisms","mystique","mystiques","mysterious","mysteriously",
  "mysteriousness","mystery","mysteries","mysterial","mysteried","mysteriing","mysteri-ness","mysteriousness","enigma","enigmas",
  "enigmatic","enigmatically","enigmatical","enigmaticity","puzzle","puzzles","puzzled","puzzling","puzzlement","puzzlements",
  "riddle","riddles","riddled","riddling","riddler","riddlers","secret","secrets","secretive","secretively",
  "secretiveness","secretly","secretness","arcane","arcanely","arcaneness","arcana","arcanum","arcanums","occult",
  "occultly","occultness","occultism","occultisms","occultist","occultists","esoteric","esoterically","esotericist","esotericists",
  "esoterica","esotericism","esotericisms","hermetic","hermetically","hermeticism","hermeticisms","hermetist","hermetists","hermeticist",
  "hermeticists","hermeticist-like","alchemical","alchemically","alchemy","alchemies","alchemist","alchemists","elixir","elixirs",
  "elixirial","philosopher","philosophers","philosophical","philosophically","philosopher-king","philosopher-kings","philosopheress","philosopheresses","philosophy",
  "philosophies","philosophe","philosophes","sage","sages","sagely","sageness","sagacious","sagaciously","sagaciousness",
  "wisdom","wisdoms","wise","wiser","wisest","wisely","sapient","sapiently","sapience","sapiences",
  "fate","fates","fated","fateful","fatefully","fatefulness","destiny","destinies","destined","destining",
  "destinal","destinally","kismet","kismets","providence","providences","providential","providentially","predestination","predestinations",
  "predestined","predestinate","predestinates","predestinating","doom","dooms","doomed","dooming","doomful","doomfully",
  "doomster","doomsters","doom-laden","doomsayer","doomsayers","doomwatcher","doomwatchers","prophecy","prophecies","prophesy",
  "prophesies","prophesied","prophesying","prophet","prophets","prophetess","prophetesses","prophetlike","prophethood","prophethoods",
  "prophetic","prophetical","prophetically","oracle","oracles","oracular","oracularly","oracularity","oracularities","sibyl",
  "sibyls","sibylline","sibyllic","sibyllicly","sibyllinely","sibyl-like","sibyl-line","sibylline","seer","seers",
  "seeress","seeresses","seership","seerships","seerlike","seer-like","seer-craft","seer-crafts","seer-crafting","seer-craftings",
  "visionary","visionaries","vision","visions","visional","visionally","vision-like","visionary","voyant","voyants",
  "voyant","voyantess","voyantesses","voyantess-like","prognostication","prognostications","prognostic","prognostics","prognosticate","prognosticates",
  "prognosticated","prognosticating","prognosticator","prognosticators","prognosticator-like","divination","divinations","divinatory","divine","divines",
  "divined","divining","diviner","diviners","divination","divinations","augur","augurs","augured","auguring",
  "augury","auguries","auspice","auspices","auspicial","auspicially","auspicious","auspiciously","auspiciousness","omen",
  "omens","omened","omening","ominous","ominously","ominousness","portent","portents","portented","portenting",
  "portentous","portentously","portentousness","presage","presages","presaged","presaging","presager","presagers","presagement",
  "harbinger","harbingers","harbingered","harbingering","harbinger-like","harbinger-ship","harbinger-ships","prefigure","prefigures","prefigured",
  "prefiguring","prefiguration","prefigurations","prefigurative","prefiguratively","prefigural","prefigurally","prefigurement","prefigurements","forerunner",
  "forerunners","foreran","forerunning","foreruns","herald","heralds","heralded","heralding","heraldic","heraldically",
  "heraldry","heraldries","precursor","precursors","precursory","precursorial","precursor-like","prototype","prototypes","prototypal",
  "prototypical","prototypically","prototypicality","archetype","archetypes","archetypal","archetypally","archetypical","archetypically","original",
  "originals","originally","originality","originalities","originalness","source","sources","sourced","sourcing","sourceful",
  "sourceless","origin","origins","originated","originating","origination","originations","originative","originatively","originator",
  // Phrases
  "the king returned","the dragon awoke","the wizard cast a spell","the knight drew his sword",
  "the hero saved the queen","the kingdom was at peace","the castle stood tall","the prophecy was fulfilled",
  "magic powers are real here","brave hearts never give up","a legend is born","destiny awaits the bold",
  "into the woods","through the valley","across the river","over the mountain","beyond the horizon",
  "the quest begins","the adventure starts","a new journey awaits","rise hero rise","stand tall stand proud",
  "magic flows through me","I am the storm","I am the light","I am the fire","I am the wind",
  "valor guides my blade","honor shields my heart","courage lights my way","wisdom speaks within","destiny calls my name",
  "the throne awaits","the crown is heavy","the scepter is heavy too","the kingdom needs a hero","the world needs saving",
  "fight on fight well","never surrender","stand your ground","hold the line","defend the realm",
  "to arms to arms","charge the enemy","for king and country","for glory and honor","for love of home",
];

// ===== SENTENCE MODE =====
export const SENTENCES_LEVEL_1 = [
  // T24: Home Row Garden — short garden sentences
  "a lad and a lass","a kid had a salad","a sad dad had a flask","dad and lass are pals",
  "all the kids ask","a dig in the mud","grass and sage","a glass of dew","hills and dells",
  "the leaf and the bud","petals on a lily","a bee in the rose","a fern by the path","the pond is still",
  "seeds in the soil","a sprout in spring","moss on a stone","the bees love the lilies","the gate is open",
];
export const SENTENCES_LEVEL_2 = [
  // T24: Top Row Sky — sky sentences
  "the bright sun","a kite in the sky","the wind is high","a bird in flight","a star at night",
  "the moon is full","a cloud in the sky","a swift bird","a tall tower","the quiet wind",
  "rays of light","wings in the air","a plane is high","a jet in the sky","the wind blew",
  "up above the clouds","the pilot wrote","a tour of the tower","the type is true","the wire is quiet",
];
export const SENTENCES_LEVEL_3 = [
  // T24: Bottom Row Ocean — ocean sentences
  "the wave is big","a crab on the sand","the seal swims","a fish in the bay","a whale in the deep",
  "the boat sails on","a dive in the sea","the ship sank","a starfish on the reef","a dolphin dives",
  "the water is cool","a shark swam by","the boat is in the bay","a turtle in the sea","an octopus dives",
  "the ocean is wide","a buoy in the bay","a sailor on a ship","a voyage to the isle","a cove by the cliff",
];
export const SENTENCES_LEVEL_4 = [
  // T24: All Letters Forest — forest sentences
  "the brown fox jumps high","green grass grows fast","deer run through the woods","birds sing in the trees",
  "frogs jump in the pond","squirrels hide acorns","butterflies flutter by","the sun shines brightly",
  "the owl hunts at night","a bear sleeps in a cave","a fox hides in the ferns","a brook runs by the oaks",
  "mushrooms grow on logs","the trail winds through the pines","a deer leaps over a log","the wild is wide",
  "ancient trees stand tall","a hawk circles above","a hummingbird drinks from a flower","the forest is alive",
];
export const SENTENCES_LEVEL_5 = [
  // T24: Capital City — capital letter sentences
  "TYPE FAST TO WIN","HOLD SHIFT FOR BIG LETTERS","THE QUICK BROWN FOX","JUMP OVER THE LAZY DOG",
  "SPRING IS A HAPPY TIME","LEARN TO TYPE EVERY DAY","MONDAY IS THE FIRST DAY","THE CITY IS BIG",
  "THE BUS STOPS HERE","THE TRAIN IS FAST","THE PLANE IS HIGH","THE BOAT IS IN THE BAY",
  "MAY IS IN THE SPRING","DECEMBER IS COLD","THE LIBRARY IS OPEN","THE TEACHER IS HERE",
  "THE DOCTOR IS KIND","THE MAYOR IS ELECTED","THE POLICE HELP US","THE FIREFIGHTER IS BRAVE",
];
export const SENTENCES_LEVEL_6 = [
  // T24: Number Galaxy — number sentences
  "123 GO FAST","COUNT TO TEN NOW","911 IS EMERGENCY","1024 BYTES EQUALS 1 KB",
  "PI IS 3.14","SPEED LIMIT 60","1 PLUS 1 IS 2","10 TIMES 10 IS 100","1000 IS A LOT",
  "THE YEAR IS 2024","THE ANSWER IS 42","FIRST PLACE IS GOLD","SECOND PLACE IS SILVER",
  "365 DAYS IN A YEAR","52 WEEKS IN A YEAR","12 HOURS ON A CLOCK","24 HOURS IN A DAY",
  "60 MINUTES IN AN HOUR","7 DAYS IN A WEEK","100 PERCENT IS ALL","50 PERCENT IS HALF",
];
export const SENTENCES_LEVEL_7 = [
  // T24: Speed Meadow — meadow sentences
  "dash past the tag","zip zap zoom","hop skip and jump","run fast win big","fly high little bird",
  "the deer leaps fast","the bee is quick","the fox runs swift","a rabbit hops fast","the horse can gallop",
  "run jump and play","zip through the meadow","the wind is fast","the stream is swift","the hawk is swift",
  "blaze through the field","the butterfly flits","the dragonfly darts","the grasshopper jumps","the hare runs fast",
];
export const SENTENCES_LEVEL_8 = [
  // T24: Accuracy Peak — peak sentences
  "climb every mountain","reach for the sky","slow and steady wins","focus on each letter",
  "be precise and careful","steady wins the race","patience on the peak","the view from the top",
  "climb with courage","the summit is high","the mountain is grand","the trail is steep",
  "climber ascend the peak","steady on the rope","the alpine snow","the glacier is cold",
  "the altitude is high","the pinnacles are sharp","the crag is jagged","the ledge is narrow",
];
export const SENTENCES_LEVEL_9 = [
  // T24: Master Valley — valley sentences
  "cross the wide valley","walk the winding path","swim the deep river","climb the steep hill",
  "ford the river at the bend","bridge the gap","the valley is green","the path winds through the glen",
  "venture through the dale","journey across the land","master the winding road","traverse the hills",
  "the bridge spans the river","the pass goes over the ridge","the ford is shallow","the trail leads on",
  "the meadow is wide","the creek runs through","the brook babbles by","the vale is peaceful",
  "a master of the way","a sage of the path","a hero of the journey","a champion of the road",
];
export const SENTENCES_LEVEL_10 = [
  // T24: Legend Kingdom — kingdom sentences
  "the wizard casts a spell","the dragon breathes fire","the hero saves the queen","the knight finds gold",
  "magic powers are real here","brave hearts never give up","the king sits on the throne","the queen wears a crown",
  "the prince draws his sword","the princess climbs the tower","the castle stands on a hill","the wizard is wise",
  "the dragon guards the gold","the knight slays the beast","the witch brews a potion","the oracle sees the future",
  "the prophecy comes true","the kingdom is at peace","the warrior fights for honor","the sage advises the king",
  "the treasure is in the chest","the gem glows in the dark","the spell is very old","the ancient scroll tells a tale",
  "destiny calls the hero","valor guides the blade","honor shields the heart","courage lights the way",
  "the royal court is grand","the mighty fortress stands","the enchanted forest whispers","the mystic knows the truth",
];

export const ALL_WORDS = {
  1: WORDS_LEVEL_1,
  2: WORDS_LEVEL_2,
  3: WORDS_LEVEL_3,
  4: WORDS_LEVEL_4,
  5: WORDS_LEVEL_5,
  6: WORDS_LEVEL_6,
  7: WORDS_LEVEL_7,
  8: WORDS_LEVEL_8,
  9: WORDS_LEVEL_9,
  10: WORDS_LEVEL_10,
};

export const ALL_SENTENCES = {
  1: SENTENCES_LEVEL_1,
  2: SENTENCES_LEVEL_2,
  3: SENTENCES_LEVEL_3,
  4: SENTENCES_LEVEL_4,
  5: SENTENCES_LEVEL_5,
  6: SENTENCES_LEVEL_6,
  7: SENTENCES_LEVEL_7,
  8: SENTENCES_LEVEL_8,
  9: SENTENCES_LEVEL_9,
  10: SENTENCES_LEVEL_10,
};
